### ISSUE TITLE
Errors when do gradlew build

### ISSUE THREAD

**Issue by zapburp** [storj/uplink-java#1]
So I tried to build the library, but when execute `gradlew.bat build` command, it throws error:

 ```
> Task :javadoc
L:\uplink-java\src\main\java\io\storj\ObjectOutputStream.java:87: error: tag not supported in the generated HTML version: tt
     * <code>b</code>, then an <tt>IndexOutOfBoundsException</tt> is thrown.
                               ^
1 error

> Task :javadoc FAILED

FAILURE: Build failed with an exception.
```

This can be fixed by replacing `<tt></tt>` with `<code></code>`. But then we get new errors:

```
> Task :test

io.storj.UplinkTest > testObjects FAILED
    java.lang.UnsatisfiedLinkError at UplinkTest.java:39

io.storj.UplinkTest > testObjectsListing FAILED
    java.lang.NoClassDefFoundError at UplinkTest.java:39

io.storj.UplinkTest > testUploadDownloadParallel FAILED
    java.lang.NoClassDefFoundError at UplinkTest.java:39

io.storj.UplinkTest > testBuckets FAILED
    java.lang.NoClassDefFoundError at UplinkTest.java:39

io.storj.UplinkTest > testPermissions FAILED
    java.lang.NoClassDefFoundError at UplinkTest.java:39

io.storj.UplinkTest > testAccess FAILED
    java.lang.NoClassDefFoundError at UplinkTest.java:39

io.storj.UplinkTest > testErrors FAILED
    java.lang.NoClassDefFoundError at UplinkTest.java:39

7 tests completed, 7 failed

> Task :test FAILED

FAILURE: Build failed with an exception.
```

Or maybe I do something wrong and there is the right to use the library?

**Comment by mniewrzal** [comment]
hey @zapburp 
the library is usable but it's still not ready to be easily consumed. This library requires a shared library for your os (from what I see its Windows) which can be built from https://github.com/storj/uplink-c. Unfortunately, atm you would need to compile `uplink-c` on your own. I can try to guide you if you are interested.

**Comment by zapburp** [comment]
Thank you @mniewrzal ! It would be nice. I used `go build -o uplink.dll -buildmode=c-shared` command to build the dll. Then I placed it in project dir, but when I try to execute `Access.parse()` function I get:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up function 'parse_access': The specified procedure could not be found.

	at com.sun.jna.Function.<init>(Function.java:252)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:600)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:576)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:562)
	at com.sun.jna.Library$Handler.invoke(Library.java:243)
	at io.storj.$Proxy0.parse_access(Unknown Source)
	at io.storj.Access.parse(Access.java:41)
	at storj.F.main(F.java:9)
```

**Comment by mniewrzal** [comment]
You may try setting `java.library.path` as your directory with dll. Also `uplink-java` is using JNA to use `uplink-c` shared library so you can try `Library Search Paths` from https://java-native-access.github.io/jna/4.2.1/com/sun/jna/NativeLibrary.html.

**Comment by harrymaurya05** [comment]
Hii @mniewrzal  and @zapburp
I am facing the same issue. Is it working for you now @zapburp?
if yes please guide me.
java.lang.UnsatisfiedLinkError: Unable to load library 'uplink':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.

Native library (win32-x86-64/uplink.dll) not found in resource path

**Comment by mniewrzal** [comment]
Hi @harrymaurya05,
You can try methods for loading shared library from this article https://www.chilkatsoft.com/java-loadLibrary-Windows.asp.

**Comment by harrymaurya05** [comment]
@mbouzi @zapburp 
I am getting this error while building the dll file using the command go build -o uplink.dll -buildmode=c-shared.
Can you guide me on what I am doing wrong?
Thank you
# storj.io/common/socket
C:\Users\HP\go\pkg\mod\storj.io\common@v0.0.0-20210113135631-07a5dc68dc1c\socket\dscp.go:17:19: syntax error: unexpecte
 b110000, expecting semicolon or newline or )
note: module requires Go 1.14
# storj.io/drpc/drpcwire
C:\Users\HP\go\pkg\mod\storj.io\drpc@v0.0.16\drpcwire\packet.go:99:24: syntax error: unexpected b00000001, expecting )
C:\Users\HP\go\pkg\mod\storj.io\drpc@v0.0.16\drpcwire\packet.go:100:27: syntax error: unexpected b10000000, expecting )
C:\Users\HP\go\pkg\mod\storj.io\drpc@v0.0.16\drpcwire\packet.go:101:29: syntax error: unexpected b01111110, expecting )
C:\Users\HP\go\pkg\mod\storj.io\drpc@v0.0.16\drpcwire\packet.go:125:15: syntax error: unexpected b00000001 at end of st
tement
C:\Users\HP\go\pkg\mod\storj.io\drpc@v0.0.16\drpcwire\packet.go:128:15: syntax error: unexpected b10000000 at end of st
tement
note: module requires Go 1.13
# storj.io/uplink/private/eestream
C:\Users\HP\go\pkg\mod\storj.io\uplink@v1.4.5\private\eestream\stripe.go:170:6: undefined: errors.Is
C:\Users\HP\go\pkg\mod\storj.io\uplink@v1.4.5\private\eestream\stripe.go:171:4: undefined: errors.Is
note: module requires Go 1.13

**Comment by mniewrzal** [comment]
What is your `go version`? Also, are you executing `go build...` from `storj/uplink-c` directory?

**Comment by harrymaurya05** [comment]
@mniewrzal 
go version go1.12.9 windows/amd64 
yes i am executing `go build ...` from `storj/uplink-c` diectory.

**Comment by mniewrzal** [comment]
Then it looks you need to update your go version to at least 1.13 but ideally to 1.15.7 https://golang.org/dl/.

**Comment by harrymaurya05** [comment]
Thanks now 
uplink.dll file generated successfully after updating go.
can you please guide me on where I need to place this file in the project.

**Comment by mniewrzal** [comment]
Can you show your code?

**Comment by harrymaurya05** [comment]
I am facing this issue while  executing `uplink-java/src/test/java/io/storj/UplinkTest.java` file using junit.

JNAUplink.AccessResult.ByValue result = JNAUplink.INSTANCE.parse_access(serialized);
ExceptionUtil.handleError(result.error);
JNAUplink.INSTANCE.free_access_result(result);
return new Access(serialized);

**Comment by mniewrzal** [comment]
To run unit tests we are setting `LD_LIBRARY_PATH` to a directory that contains uplink shared library file, see
https://github.com/storj/uplink-java/blob/main/scripts/test-libuplink.sh#L6

**Comment by harrymaurya05** [comment]
i have update the lib path as you described.
its throw android related error now
![image](https://user-images.githubusercontent.com/22474692/105889017-b454ff80-6033-11eb-8d9a-9fca90a2e810.png)

**Comment by harrymaurya05** [comment]
@mniewrzal 
I have changed the path of uplink-c in the script but it not giving me any output or something. 
**Script**
'#!/bin/bash
set -ueo pipefail
set +x

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

go install \
	storj.io/storj/cmd/certificates \
	storj.io/storj/cmd/identity \
	storj.io/storj/cmd/satellite \
	storj.io/storj/cmd/storagenode \
	storj.io/storj/cmd/versioncontrol \
	storj.io/storj/cmd/storj-sim

go install storj.io/gateway

# setup tmpdir for testfiles and cleanup
TMP=$(mktemp -d -t tmp.XXXXXXXXXX)
cleanup(){
      rm -rf "$TMP"
}
trap cleanup EXIT

mkdir -p $SCRIPTDIR/../.build
go build -ldflags="-s -w" -buildmode c-shared -o $SCRIPTDIR/../.build/libuplink.so ..\..\uplink-c

export STORJ_NETWORK_DIR=$TMP

STORJ_NETWORK_HOST4=${STORJ_NETWORK_HOST4:-127.0.0.1}

# setup the network
storj-sim -x --host $STORJ_NETWORK_HOST4 network setup

# run tests
storj-sim -x --host $STORJ_NETWORK_HOST4 network test bash "$SCRIPTDIR/test-libuplink.sh"
storj-sim -x --host $STORJ_NETWORK_HOST4 network destroy
'
![image](https://user-images.githubusercontent.com/22474692/105892309-ae611d80-6037-11eb-8ab0-efe897ce82c5.png)

**Comment by harrymaurya05** [comment]
Hii @mniewrzal 
as you suggest to add uplink.dll file path in 'LD_LIBRARY_PATH' after follow same step still I am facing issue 
**test-libuplink.sh script**
#!/bin/bash
set -ueo pipefail

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

export LD_LIBRARY_PATH=$SCRIPTDIR/../../uplink-c
./gradlew clean test

**error**
Starting process 'Gradle Test Executor 7'. Working directory: F:\storj\uplink-java Command: C:\Program Files\Java\jdk-12
.0.2\bin\java.exe -Djna.encoding=UTF8 -Dorg.gradle.native=false @C:\Users\HP\AppData\Local\Temp\gradle-worker-classpath1
5858464777287385388txt -Xmx512m -Dfile.encoding=windows-1252 -Duser.country=IN -Duser.language=en -Duser.variant -ea wor
ker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 7'
Successfully started process 'Gradle Test Executor 7'
'
io.storj.UplinkTest > testObjects FAILED
    java.lang.UnsatisfiedLinkError: Error looking up function 'parse_access': The specified procedure could not be found
.
        at com.sun.jna.Function.<init>(Function.java:252)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:594)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:570)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:556)
        at com.sun.jna.Library$Handler.invoke(Library.java:243)
        at io.storj.$Proxy12.parse_access(Unknown Source)
        at io.storj.Access.parse(Access.java:41)
        at io.storj.UplinkTest.setUp(UplinkTest.java:46)'

**Comment by elek** [comment]
@harrymaurya05 uplink-java was compatible only an older version of uplink-c. I created a PR (#3) which makes it possible to build it with recent uplink.
