### ISSUE TITLE
SystemMetadata

### ISSUE THREAD

**Issue by llyppi** [storj/uplink-java#9]
ObjectInfo[] list = project.listObjects(bucket)
all object
getSystemMetadata().getCreated() return aways 1969-12-30
getSystemMetadata().getContentLength() return aways 0

**Comment by mniewrzal** [comment]
To get `system` or `custom` metadata while listing objects you need to add option to retrive it e.g.
```java
try (ObjectIterator objectIterator = project.listObjects("my-bucket",
        ObjectListOption.system(), ObjectListOption.custom())) {
    for (ObjectInfo objectInfo : objectIterator) {
        ...
    }
}
```

**Comment by llyppi** [comment]
@mniewrzal 
its works thanks
